FROM ubuntu:16.04

MAINTAINER Ma Libo<malibo8407@gmail.com>


#RUN rm -v /etc/nginx/conf.d/default.conf

RUN apt-get -y update
RUN apt-get install -y nginx php7.0 php7.0-fpm

COPY www/info.php /var/www/html
COPY default /etc/nginx/sites-enabled/default

RUN echo 'daemon off;' >> /etc/nginx/nginx.conf

CMD service nginx start && service php7.0-fpm start

EXPOSE 80


