<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: admin
 * Date: Wed, 06 Jan 2016 15:33:59 +0000
 */

$conf['title'] = 'mywiki';
$conf['license'] = '0';
$conf['cookiedir'] = './cookies';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['userewrite'] = '1';
$conf['proxy']['user'] = 'driyan@qq.com';
$conf['proxy']['pass'] = '<b>VXNlcjAwMQ==';

// end auto-generated content
