<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: admin
 * Date: Thu, 14 Jan 2016 14:54:24 +0000
 */

$conf['title'] = 'IT Wiki';
$conf['license'] = '0';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['proxy']['user'] = 'driyan@qq.com';
$conf['proxy']['pass'] = '<b>VXNlcjAwMQ==';

// end auto-generated content
